/**
 * A permanent metamorphic property closing the exact gap D-158
 * (`docs/DECISIONS.md`) itself disclosed but deliberately left open: "a
 * permanent metamorphic property covering the general shape is real,
 * valuable, separately-scoped follow-up work this finding surfaces, not yet
 * built." D-158 fixed a real, previously-undiscovered soundness bug —
 * `exclusion`'s `subtract` branch hitting a cycle guard or depth ceiling
 * (an "unprovable disproof," `certain: false`) used to flip, via the
 * exclusion's own `NOT`, into an unsound `allowed: true` — but its own
 * regression tests are fixture-specific (one hand-built self-referencing
 * `folder` namespace, one hand-built 3-node odd ring — see
 * `test/unit/resolve/reference-resolver.graph-shape.test.ts`'s
 * `a-self-referencing-parent-tuple-...` and `a-three-node-ring-...` tests).
 * This file asserts the GENERAL property, across MANY independently
 * randomly-generated schema/tuple-graph instances, following the established
 * pattern `src/metamorphic/monotonicity.ts` +
 * `test/metamorphic/monotonicity.integration.test.ts` (D-140/D-147) already
 * set: **run against the real, unmodified production engine, no second
 * implementation needed — the property itself is the check.**
 *
 * **The exact property asserted.** For a schema containing an exclusion
 * rule (`base - subtract`) whose `subtract` branch is deliberately
 * constructed so that resolving it hits an unprovable cut — a genuine
 * tuple-data cycle the walk's own cycle guard catches, or a chain strictly
 * deeper than the check's own pinned depth budget — with `base` genuinely,
 * certainly true: the exclusion MUST resolve `DENIED` (fail-closed) against
 * the real production engine. It must NEVER resolve `ALLOWED`. An
 * `ALLOWED` result here is a `false_grant` in this project's own strict
 * sense (`docs/DECISIONS.md` D-006) — a security bug, not a mere
 * disagreement — because "cannot prove `subtract` true" is being asked to
 * stand in for "proved `subtract` false," which it structurally cannot.
 *
 * **Two independently-built shapes, one per mechanism the production
 * resolver actually has** (`src/resolve/production/resolver.ts`'s own
 * top-of-file doc comment) — generated by
 * `src/metamorphic/unprovable-exclusion-fixtures.ts` (see that file's own
 * doc comment for exactly why neither `src/schema/dsl/random.ts` nor
 * `src/soundness/generators.ts`'s `generateFixture` could be reused AS-IS
 * for this specific shape, and what was reused from each instead — the
 * seeded `SeededRng`/`hashSeedToInt31` draw-pool technique, not a new PRNG):
 *
 *   - **PROPERTY A (mechanism 1 — TS-level recursion, primary case).**
 *     `subtract` is `parent->view`, a `tupleToUserset` recursing into a
 *     PERMISSION — routes through `resolve()`'s own `visited`-Set walk,
 *     the exact mechanism D-158 fixed in both resolvers (already on `main`
 *     in this worktree). Expected GREEN here.
 *   - **PROPERTY B (mechanism 2 — SQL relation-membership, secondary
 *     case).** `subtract` is a bare `computedUserset` naming a plain
 *     declared RELATION with a self-referential userset subject type —
 *     routes through `sqlRelationMembershipWithWitness` instead. D-158's
 *     own report explicitly disclosed this mechanism's depth ceiling as
 *     sharing "the identical theoretical flip risk" but NOT fixed by that
 *     entry ("`RelationDisproof` carries no 'was the ceiling actually still
 *     binding' signal today... tracked as separate, not-yet-built
 *     follow-up work, not assumed closed by this fix"). This property was
 *     first written in a worktree that did not yet have that fix, and its
 *     own local run correctly, honestly FAILED on the core cutoff check —
 *     exactly the residual D-158 disclosed (`docs/DECISIONS.md` D-160). A
 *     SIBLING investigation independently confirmed the residual was real
 *     and live-reproducible and fixed it (`docs/DECISIONS.md` D-159):
 *     `resolve()`'s relation branch now propagates `sqlOutcome.certain`
 *     (via the new `depthCeilingGenuinelyBinding` helper) instead of
 *     hardcoding `certain: true`. Once that fix merged into this worktree,
 *     PROPERTY B was re-run live and now passes with no changes to this
 *     file at all (D-160's own "Update") — a second, independent
 *     confirmation of D-159's own live reproduction. Expected GREEN here
 *     too. See PROPERTY B's own describe block for the current, accurate
 *     accounting.
 *
 * **Convention** — identical to `monotonicity.integration.test.ts`'s own
 * established `PostgreSqlContainer` precedent (see that file's own top doc
 * comment for the full history of why `DATABASE_URL`-only didn't
 * generalize). A sandbox without a reachable Docker daemon uses this
 * project's own established LOCALVERIFY accommodation instead: swap the
 * container-based `beforeAll`/`afterAll` below for a direct connection pool,
 * run, then restore this file's exact committed, container-based form
 * before shipping.
 */
import { fileURLToPath } from 'node:url';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { Pool } from 'pg';
import { PostgreSqlContainer, type StartedPostgreSqlContainer } from '@testcontainers/postgresql';

import { writeTuple, type TupleKey } from '../../src/store/tuples.js';
import { publishSchema } from '../../src/schema/publish.js';
import { productionCheck } from '../../src/resolve/production/resolver.js';
import { runMigrations } from '../../src/store/migrate.js';
import { rebuildRelationMembershipIndex } from '../../src/store/relation-index.js';
import {
  buildMechanism1Fixture,
  buildMechanism2Fixture,
  type FixtureTuple,
} from '../../src/metamorphic/unprovable-exclusion-fixtures.js';

const MIGRATIONS_DIR = fileURLToPath(new URL('../../src/store/migrations', import.meta.url));

let container: StartedPostgreSqlContainer;
let pool: Pool;

beforeAll(async () => {
  container = await new PostgreSqlContainer('postgres:16-alpine').start();
  pool = new Pool({ connectionString: container.getConnectionUri() });
  pool.on('error', (err) => {
    // pg's own documented contract — see the identical comment in every
    // sibling *.integration.test.ts file in this repo: without this, an
    // idle client hitting a background/network-level error (most commonly
    // this file's own container being stopped in afterAll while a pooled
    // connection was still technically open) crashes the whole test run
    // with an unhandled 'error' event, even though every real assertion
    // already passed. Logged, not swallowed.
    console.error(`pool error (expected during container teardown): ${err.message}`);
  });
  await runMigrations(pool, MIGRATIONS_DIR);
}, 180_000);

afterAll(async () => {
  await pool.end();
  await container.stop();
});

// ---------------------------------------------------------------------------
// Shared helpers — deliberately small and local to this file, matching this
// repo's own established per-integration-test-file convention (see
// `docs/DECISIONS.md` D-022's general "don't force accidental coupling
// between independent test files" reasoning, applied here to test helpers).
// ---------------------------------------------------------------------------

let uniqueCounter = 0;
const processSalt = Math.random().toString(36).slice(2, 10);
/** A fresh lowercase identifier, unique across this and sibling test files/workers, matching IDENTIFIER_PATTERN (`^[a-z][a-z0-9_]*$`). */
function uniqueName(prefix: string): string {
  uniqueCounter += 1;
  return `${prefix}_${Date.now().toString(36)}_${processSalt}_${uniqueCounter}`;
}

interface Ref {
  ns: string;
  id: string;
}

function ref(ns: string, id: string): Ref {
  return { ns, id };
}

function toTupleKey(t: FixtureTuple): TupleKey {
  return {
    objectNs: t.objectNs,
    objectId: t.objectId,
    relation: t.relation,
    subjectNs: t.subjectNs,
    subjectId: t.subjectId,
    ...(t.subjectRelation !== undefined ? { subjectRelation: t.subjectRelation } : {}),
  };
}

/** Publishes `source` and fails the test (with the real errors) if it doesn't compile/publish. */
async function publishOk(source: string): Promise<void> {
  const result = await publishSchema(pool, source);
  if (!result.ok) {
    throw new Error(`fixture schema failed to publish: ${result.errors.join('; ')}`);
  }
}

/** Writes `t` for real and fails the test if the store rejects it. */
async function writeOk(t: FixtureTuple): Promise<{ token: number; created: boolean }> {
  const result = await writeTuple(pool, toTupleKey(t));
  if (!result.ok) {
    throw new Error(`fixture tuple failed to write: ${JSON.stringify(result.errors)}`);
  }
  return { token: result.token, created: result.created };
}

/** Writes every tuple in `tuples`, SEQUENTIALLY (never `Promise.all`) — matching `src/soundness/runner.ts`'s own real write-phase convention and every sibling `*.integration.test.ts` file's own identical discipline, required for the strict happens-before ordering an `atToken`-pinned check below depends on. Returns the LAST write's own token. */
async function writeAllSequentially(
  seed: string,
  tuples: readonly FixtureTuple[],
): Promise<number> {
  let lastToken: number | undefined;
  for (const t of tuples) {
    const written = await writeOk(t);
    lastToken = written.token;
  }
  if (lastToken === undefined) {
    throw new Error(
      `seed=${seed}: fixture produced zero tuples — a generator bug, not a property finding`,
    );
  }
  return lastToken;
}

// ---------------------------------------------------------------------------
// PROPERTY A — mechanism 1 (TS-level `visited`-Set recursion)
// ---------------------------------------------------------------------------

describe('Property A — an exclusion subtract branch that hits a TS-level cycle guard or depth ceiling must never grant (mechanism 1, general sweep)', () => {
  const SEED_COUNT = 40;

  it(`across ${SEED_COUNT} random seeds (mixing genuine tuple-data cycles of varying ring length and non-cyclic chains deeper than a pinned depth budget), the exclusion never resolves ALLOWED for the unprovable node(s), and a genuinely-short, certainly-not-excluded control on the SAME schema still resolves ALLOWED (never denies everything)`, async () => {
    let cycleSeeds = 0;
    let depthCeilingSeeds = 0;
    let totalUnprovableChecks = 0;
    let totalControlChecks = 0;

    for (let seedIndex = 0; seedIndex < SEED_COUNT; seedIndex += 1) {
      const seed = uniqueName(`m1prop${seedIndex}`);
      const fixture = buildMechanism1Fixture(seed);
      if (fixture.cutKind === 'cycle') cycleSeeds += 1;
      else depthCeilingSeeds += 1;

      await publishOk(fixture.schemaSource);
      const lastToken = await writeAllSequentially(seed, fixture.tuples);

      for (const queryObjectId of fixture.unprovableQueryObjectIds) {
        totalUnprovableChecks += 1;
        const result = await productionCheck(
          pool,
          ref('user', fixture.subjectId),
          ref(fixture.namespace, queryObjectId),
          fixture.permissionName,
          { atToken: lastToken, maxDepth: fixture.pinnedMaxDepth },
        );
        expect(
          result.allowed,
          `${fixture.description}\nqueryObjectId=${queryObjectId}: '${fixture.permissionName}' resolved ALLOWED for a subtract branch that hit an unprovable cut (${fixture.cutKind}) — this is a false_grant, the exact soundness bug D-158 fixed for this shape (see docs/DECISIONS.md D-158); base was granted and subtract could only be neither-proven-nor-disproven, so the exclusion must fail closed`,
        ).toBe(false);
      }

      totalControlChecks += 1;
      const controlResult = await productionCheck(
        pool,
        ref('user', fixture.subjectId),
        ref(fixture.namespace, fixture.controlQueryObjectId),
        fixture.permissionName,
        { atToken: lastToken, maxDepth: fixture.pinnedMaxDepth },
      );
      expect(
        controlResult.allowed,
        `${fixture.description}\ncontrol object '${fixture.controlQueryObjectId}' (a genuinely short, certainly-not-excluded exclusion on the SAME schema/budget) resolved DENIED — the fix must not be over-conservative and deny every exclusion under this budget, only the genuinely unprovable ones`,
      ).toBe(true);
    }

    console.log(
      `[Property A] ${SEED_COUNT} seeds (${cycleSeeds} cycle-shaped, ${depthCeilingSeeds} depth-ceiling-shaped); ` +
        `${totalUnprovableChecks} unprovable-node checks (every one asserted DENIED), ${totalControlChecks} control checks (every one asserted ALLOWED)`,
    );

    // "A property that never actually exercises anything is worse than
    // useless and must be flagged, not silently reported as 'passing'" —
    // matching Property 4/5's own established discipline in
    // monotonicity.integration.test.ts.
    expect(
      cycleSeeds,
      'Property A drew ZERO cycle-shaped seeds across the whole sweep — either a real RNG-distribution bug in buildMechanism1Fixture, or this property never actually exercised the cycle-guard shape',
    ).toBeGreaterThan(0);
    expect(
      depthCeilingSeeds,
      'Property A drew ZERO depth-ceiling-shaped seeds across the whole sweep — either a real RNG-distribution bug in buildMechanism1Fixture, or this property never actually exercised the depth-ceiling shape',
    ).toBeGreaterThan(0);
    expect(totalUnprovableChecks).toBeGreaterThan(0);
    expect(totalControlChecks).toBe(SEED_COUNT);
  }, 600_000);
});

// ---------------------------------------------------------------------------
// PROPERTY B — mechanism 2 (`sqlRelationMembershipWithWitness`)
// ---------------------------------------------------------------------------

describe('Property B — an exclusion subtract branch that hits the SQL relation-membership depth ceiling must never grant (mechanism 2, general sweep)', () => {
  /**
   * **History, kept for the record — this property now genuinely passes.**
   * When this file was first written, `src/resolve/production/resolver.ts`'s
   * `resolve()` (relation branch) unconditionally did `{ allowed: false,
   * certain: true, disproof: sqlOutcome.disproof }` on mechanism 2's own
   * `false` outcome — confirmed by reading that file directly before writing
   * this property — and this describe block's core cutoff check correctly,
   * honestly FAILED against it (`docs/DECISIONS.md` D-160). This property's
   * own assertion was written the way it SHOULD be from the start (an
   * unprovable mechanism-2 cut must deny, exactly like Property A's
   * mechanism-1 case), never weakened to force a local pass, and
   * `resolver.ts` was left untouched by this file or its author — fixing
   * mechanism 2 was a sibling investigation's own exclusive scope
   * (`docs/DECISIONS.md` D-159): `resolve()`'s relation branch now
   * propagates `sqlOutcome.certain` (via the new
   * `depthCeilingGenuinelyBinding` helper) instead of hardcoding `certain:
   * true`. Once that fix merged into this worktree, this property was
   * re-run live and now passes with no changes to this file at all — a
   * second, independent confirmation of D-159's own live reproduction. If
   * this ever fails again, that fix has regressed — treat it as a real
   * finding, not an expected result.
   */
  const SEED_COUNT = 10;

  it(`across ${SEED_COUNT} random seeds (varying nested-group chain length), a subject who IS genuinely a member of the exclusion's own 'subtract' relation — just past a pinned maxDepth that cannot reach that real membership — must resolve the exclusion DENIED, never ALLOWED`, async () => {
    let totalCutoffChecks = 0;
    let totalNaturalBoundaryChecks = 0;
    let totalSanityChecks = 0;

    for (let seedIndex = 0; seedIndex < SEED_COUNT; seedIndex += 1) {
      const seed = uniqueName(`m2prop${seedIndex}`);
      const fixture = buildMechanism2Fixture(seed);

      await publishOk(fixture.schemaSource);
      const lastToken = await writeAllSequentially(seed, fixture.tuples);

      // Sanity control, run FIRST (generous, explicit maxDepth — far beyond
      // any accounting concern): confirms this seed's own chain is a REAL,
      // provable membership, not a phantom one this generator failed to
      // wire up correctly. If this ever fails, that's a generator defect in
      // `buildMechanism2Fixture`, not a resolver finding.
      totalSanityChecks += 1;
      const sanityResult = await productionCheck(
        pool,
        ref('user', fixture.subjectId),
        ref(fixture.docNamespace, fixture.queryObjectId),
        fixture.permissionName,
        { atToken: lastToken, maxDepth: 1000 },
      );
      expect(
        sanityResult.allowed,
        `${fixture.description}\nsanity check at maxDepth=1000 expected '${fixture.permissionName}' DENIED (subject is genuinely, really blocked via a real ${fixture.chainLength}-hop chain — not a phantom one) — got ALLOWED, which means this generator's own fixture is broken, not a resolver finding`,
      ).toBe(false);

      // The natural boundary — maxDepth exactly large enough to reach the
      // real terminal membership. Expected to pass REGARDLESS of the
      // disclosed mechanism-2 gap: when the SQL walk genuinely, certainly
      // FINDS the membership, `subtract.allowed === true` and the exclusion
      // denies via the ordinary `subtractProven` path, untouched by the
      // `certain` plumbing this property's own cutoff check below is about.
      totalNaturalBoundaryChecks += 1;
      const boundaryResult = await productionCheck(
        pool,
        ref('user', fixture.subjectId),
        ref(fixture.docNamespace, fixture.queryObjectId),
        fixture.permissionName,
        { atToken: lastToken, maxDepth: fixture.naturalBoundaryMaxDepth },
      );
      expect(
        boundaryResult.allowed,
        `${fixture.description}\nat the natural boundary maxDepth=${fixture.naturalBoundaryMaxDepth} (exactly enough budget to reach the real terminal membership), expected '${fixture.permissionName}' DENIED via a genuine, certain proof of 'blocked' — this should hold regardless of the disclosed mechanism-2 gap`,
      ).toBe(false);

      // *** The property's own core assertion — see this describe block's
      // own top doc comment for why this now genuinely passes. ***
      totalCutoffChecks += 1;
      const cutoffResult = await productionCheck(
        pool,
        ref('user', fixture.subjectId),
        ref(fixture.docNamespace, fixture.queryObjectId),
        fixture.permissionName,
        { atToken: lastToken, maxDepth: fixture.cutoffMaxDepth },
      );
      expect(
        cutoffResult.allowed,
        `${fixture.description}\nat maxDepth=${fixture.cutoffMaxDepth} (one hop short of the real terminal membership), '${fixture.permissionName}' resolved ALLOWED — a false_grant via mechanism 2's own depth-ceiling gap (sqlRelationMembershipWithWitness reporting certain:true unconditionally on its own 'false'). This gap was fixed in docs/DECISIONS.md D-159 (resolve()'s relation branch now propagates sqlOutcome.certain via depthCeilingGenuinelyBinding); if this ever fails again, that fix has regressed — treat it as a real finding, not an expected result.`,
      ).toBe(false);
    }

    console.log(
      `[Property B] ${SEED_COUNT} seeds; ${totalSanityChecks} sanity checks, ` +
        `${totalNaturalBoundaryChecks} natural-boundary checks, ${totalCutoffChecks} cutoff checks ` +
        `(every cutoff check correctly asserted DENIED — mechanism 2's own depth-ceiling gap, ` +
        `docs/DECISIONS.md D-159, is fixed and merged in this worktree)`,
    );

    expect(totalCutoffChecks).toBe(SEED_COUNT);
  }, 600_000);
});

// ---------------------------------------------------------------------------
// Leopard index Candidate F — the depth-length gate, checked against this
// file's own Property B fixtures (`docs/LEOPARD-INDEX-PROPOSAL.md`)
// ---------------------------------------------------------------------------

/**
 * **Extended, not replaced** (`docs/LEOPARD-INDEX-PROPOSAL.md`'s own
 * file-by-file test plan, the row naming this exact file): re-runs Property
 * B's own `buildMechanism2Fixture` seeded shapes with the Leopard index
 * WARMED by an uncapped rebuild (`rebuildRelationMembershipIndex` — "No
 * depth ceiling on this recursion," deliberately, per the proposal's own
 * "The rebuild" section) at a real depth strictly LARGER than the pinned
 * `maxDepth` values used below. `atToken` for every check is pinned to
 * exactly that rebuild's own returned `watermarkToken`.
 *
 * **An adversarial finding, disclosed rather than silently worked around:
 * checking `fixture.permissionName` ('view', the `grant - blocked`
 * exclusion) at `cutoffMaxDepth` — the shape this task's own instructions
 * first pointed at — CANNOT actually fail-check Candidate F's depth-length
 * gate, and a fail-check confirmed this live before this file was trusted.**
 * `blocked` sits in the exclusion's own NEGATED (`subtract`) position.
 * Tracing `resolver.ts`'s real `exclusion` case: if `subtract.allowed ===
 * true` (an index hit for `blocked`, regardless of how long its stored path
 * is), the exclusion resolves `allowed: false` (denied) via the ordinary
 * `subtractProven` path — safe, by construction, in the ALLOW-only-index
 * direction, since a *bigger* index (longer permitted path) can only ever
 * make `blocked` *more* likely to be found true, which only ever makes
 * `view` *more* likely to (correctly, safely) deny. And per the D-158 fix
 * already landed in this worktree (see `case 'exclusion'` in
 * `resolver.ts`), an *uncertain* `subtract` (the live-CTE fallback on a
 * genuine index miss) ALSO makes the exclusion fail closed to `denied`. Both
 * of Candidate F's own "gate present" and "gate absent" branches therefore
 * lead to the IDENTICAL `denied` outcome for `view` — a broken gate cannot
 * flip this specific check to `allowed: true` at all. A live fail-check
 * (disabling the gate entirely and re-running the `view`-level assertion)
 * confirmed this directly: the assertion stayed GREEN with the gate
 * disabled, proving it was never capable of catching this bug. **Do not
 * mistake a `view`-level assertion here for a real Candidate F proof — it
 * is kept below only as a non-regression sanity check (a different, real
 * failure mode: Leopard index enabled must not somehow break Property B's
 * own now-passing exclusion behavior), explicitly labeled as such.**
 *
 * **The property this file actually load-bears Candidate F with: a DIRECT,
 * top-level check on the bare `blocked` RELATION itself** (never through
 * `view`'s own negation) — the positive-position shape
 * `docs/LEOPARD-INDEX-PROPOSAL.md`'s own Candidate F fail-check names
 * verbatim: "run a check pinned to `maxDepth: 3` against a subject only
 * reachable at depth 5 through the index's stored path; confirm it now
 * wrongly reports ALLOWED, while the same check with the index off...
 * correctly reports DENIED." A direct top-level check on a bare relation
 * enters `resolve()` at `depth = 0` (no permission-entry `+1`), so
 * `remainingDepth = maxDepth` exactly, with NO offset to account for
 * (unlike a check nested inside `view`'s own exclusion, where `subtract`
 * only ever receives `ctx.maxDepth - 1` — this file's own
 * `Mechanism2Fixture.cutoffMaxDepth` doc comment states that derivation).
 * The real, uncapped rebuild materializes `blocked`'s own full,
 * `chainLength`-hop-deep membership chain (verified directly against the
 * real `relation_membership_index` table below, never merely assumed).
 * Checking `blocked` directly at `maxDepth: fixture.chainLength - 1` (one
 * hop short of what the live CTE needs — `fetchReachableFrontier`'s own
 * `m.depth < maxDepth` requirement, per this fixture's own doc comment)
 * must MISS the too-long stored row and fall through to a genuinely
 * uncertain live-CTE `denied`; a broken gate instead wrongly serves the
 * stored hit regardless of budget, flipping this direct check to a live,
 * reproducible `ALLOWED` — an index_false_grant. A positive control at
 * `maxDepth: fixture.chainLength` (exactly sufficient) confirms the SAME
 * stored row correctly HITS one hop of budget later, ruling out "the index
 * never engaged with this fixture at all" as an alternative explanation for
 * the miss.
 */
describe("Leopard index Candidate F — the depth-length gate must reject a rebuild-discovered path longer than the checking call's own remaining depth budget (mechanism 2, this file's own Property B fixtures, rebuild depth LARGER than the pinned maxDepth)", () => {
  const SEED_COUNT = 10;

  it(`across ${SEED_COUNT} random seeds (varying nested-group chain length), an UNCAPPED rebuild that genuinely discovers the real 'blocked' membership chain must still leave a DIRECT, top-level index-accelerated check on 'blocked' one hop short of budget DENIED, never a false ALLOW from the index silently overriding the caller's own narrower depth budget; the SAME stored row must correctly HIT one hop of budget later; Property B's own exclusion-level check must not regress either way`, async () => {
    let totalCutoffChecks = 0;
    let totalNaturalBoundaryChecks = 0;
    let totalExclusionRegressionChecks = 0;
    let rowsConfirmedRealLength = 0;

    for (let seedIndex = 0; seedIndex < SEED_COUNT; seedIndex += 1) {
      const seed = uniqueName(`leopardF${seedIndex}`);
      const fixture = buildMechanism2Fixture(seed);

      await publishOk(fixture.schemaSource);
      await writeAllSequentially(seed, fixture.tuples);

      // No depth cap, ever ("No depth ceiling on this recursion",
      // docs/LEOPARD-INDEX-PROPOSAL.md's own "The rebuild" section) — the
      // rebuild discovers the REAL, full-length 'blocked' membership chain
      // regardless of how small the pinned maxDepth values checked below
      // are. Zero writes happen between this rebuild and every check below
      // for this seed.
      const rebuildResult = await rebuildRelationMembershipIndex(pool);
      expect(
        rebuildResult.lockAcquired,
        `${fixture.description}\nseed=${seed}: the rebuild's advisory lock was not acquired — cannot proceed with this seed`,
      ).toBe(true);
      expect(
        rebuildResult.published,
        `${fixture.description}\nseed=${seed}: the rebuild did not publish`,
      ).toBe(true);
      const pinToken = rebuildResult.watermarkToken;

      // Non-vacuity, live-queried directly against the real table (never
      // trusted from the rebuild's own row count alone): the row this
      // whole property depends on must actually exist, and its real
      // via_path hop count must genuinely equal this fixture's own
      // chainLength — otherwise a "miss" below would be trivially true for
      // the wrong reason (no row at all), never because the length gate
      // did its job.
      const { rows: indexRows } = await pool.query<{ via_path: string[] }>(
        `select via_path from relation_membership_index
           where object_ns = $1 and object_id = $2 and relation = 'blocked'
             and subject_ns = 'user' and subject_id = $3`,
        [fixture.docNamespace, fixture.queryObjectId, fixture.subjectId],
      );
      const indexedRow = indexRows[0];
      expect(
        indexedRow,
        `${fixture.description}\nseed=${seed}: the uncapped rebuild did not materialize a 'blocked' membership row at all — this test cannot exercise the length gate without one`,
      ).toBeDefined();
      const storedHopCount = (indexedRow?.via_path.length ?? 0) - 1;
      expect(
        storedHopCount,
        `${fixture.description}\nseed=${seed}: the rebuild's own stored via_path hop count (${storedHopCount}) does not match this fixture's real chainLength (${fixture.chainLength}) — a generator/rebuild mismatch, not a resolver finding`,
      ).toBe(fixture.chainLength);
      rowsConfirmedRealLength += 1;

      // *** The core, load-bearing Candidate F assertion: a DIRECT,
      // top-level check on the bare 'blocked' relation, one hop short of
      // the real chain's own length, with the index enabled. ***
      const directCutoffMaxDepth = fixture.chainLength - 1;
      totalCutoffChecks += 1;
      const directCutoffResult = await productionCheck(
        pool,
        ref('user', fixture.subjectId),
        ref(fixture.docNamespace, fixture.queryObjectId),
        'blocked',
        { atToken: pinToken, maxDepth: directCutoffMaxDepth, useRelationIndex: true },
      );
      expect(
        directCutoffResult.allowed,
        `${fixture.description}\nseed=${seed}: a DIRECT top-level check on 'blocked' at maxDepth=${directCutoffMaxDepth} (one hop short of the real, ${fixture.chainLength}-hop chain) WITH the Leopard index enabled and warmed by an uncapped rebuild resolved ALLOWED — the depth-length gate (Candidate F, docs/LEOPARD-INDEX-PROPOSAL.md) failed to reject a stored path longer than this call's own remaining depth budget, silently overriding the caller's own narrower maxDepth. This is a live index_false_grant, not a hypothetical one.`,
      ).toBe(false);

      // Positive control, same stored row, one hop more budget: proves the
      // miss above is really the length gate at work, not the index simply
      // never engaging with this fixture's shape at all for some unrelated
      // reason (e.g. a stale watermark, the wrong root).
      totalNaturalBoundaryChecks += 1;
      const directNaturalResult = await productionCheck(
        pool,
        ref('user', fixture.subjectId),
        ref(fixture.docNamespace, fixture.queryObjectId),
        'blocked',
        { atToken: pinToken, maxDepth: fixture.chainLength, useRelationIndex: true },
      );
      expect(
        directNaturalResult.allowed,
        `${fixture.description}\nseed=${seed}: a DIRECT top-level check on 'blocked' at maxDepth=${fixture.chainLength} (exactly enough budget for the real chain) WITH the index enabled resolved DENIED — the same stored row that correctly missed one hop of budget earlier should now correctly HIT; if this fails, the miss above may be for an unrelated reason (stale watermark, wrong root), not the length gate specifically`,
      ).toBe(true);

      // Non-regression sanity, NOT a Candidate F fail-check by itself (see
      // this describe block's own doc comment for why 'blocked' sitting in
      // an exclusion's negated position makes every combination of
      // index-hit/miss here safe regardless of the length gate) — confirms
      // Leopard-index acceleration does not somehow break Property B's own
      // already-fixed, now-passing exclusion behavior at its own pinned
      // cutoffMaxDepth.
      totalExclusionRegressionChecks += 1;
      const exclusionResult = await productionCheck(
        pool,
        ref('user', fixture.subjectId),
        ref(fixture.docNamespace, fixture.queryObjectId),
        fixture.permissionName,
        { atToken: pinToken, maxDepth: fixture.cutoffMaxDepth, useRelationIndex: true },
      );
      expect(
        exclusionResult.allowed,
        `${fixture.description}\nseed=${seed}: (non-regression) at maxDepth=${fixture.cutoffMaxDepth} with the Leopard index enabled, '${fixture.permissionName}' resolved ALLOWED — Property B's own already-fixed exclusion behavior regressed when the index was turned on`,
      ).toBe(false);
    }

    console.log(
      `[Leopard index Candidate F] ${SEED_COUNT} seeds; ${rowsConfirmedRealLength} rows independently ` +
        `confirmed real-length in relation_membership_index; ${totalCutoffChecks} direct one-hop-short ` +
        `checks all correctly DENIED; ${totalNaturalBoundaryChecks} direct exactly-enough-budget checks ` +
        `all correctly ALLOWED; ${totalExclusionRegressionChecks} exclusion-level non-regression checks ` +
        `all correctly DENIED`,
    );

    expect(totalCutoffChecks).toBe(SEED_COUNT);
    expect(totalNaturalBoundaryChecks).toBe(SEED_COUNT);
    expect(rowsConfirmedRealLength).toBe(SEED_COUNT);
  }, 600_000);
});
